/*
  Put your GLB files in assets/models, then make sure each `src` below
  exactly matches the file name. Spaces are okay, but spelling must match.
*/
window.PORTFOLIO_DATA = {
  person: {
    name: "Aayushman Srivastava",
    title: "Mechanical design, CAD assemblies, prototypes, and 3D model reviews.",
    summary:
      "I use CAD, prototyping, and hands-on testing to turn mechanical ideas into parts, assemblies, and systems that can be reviewed clearly.",
    about: [
      "I am a mechanical engineering student building a portfolio around real design work: CAD assemblies, mechanisms, prototype hardware, and engineering decisions.",
      "This site is set up so each project can include a GLB model, a short design summary, the tools used, and the role I played. It is meant to help recruiters understand the work quickly while still being able to inspect the geometry.",
    ],
    focus: [
      "CAD assemblies and design-for-manufacturing thinking",
      "UAV and rover hardware, fixtures, and mounting systems",
      "Clear documentation for design reviews and prototype handoff",
      "Interactive 3D presentation for mechanical portfolios",
    ],
    links: [
      { label: "View Models", href: "#models", type: "primary" },
      { label: "Resume", href: "assets/Resume.pdf" },
      { label: "Contact", href: "#contact" },
    ],
    facts: [
      { label: "Focus", value: "CAD, prototypes, mechanisms" },
      { label: "Tools", value: "SolidWorks, Fusion 360, 3D printing" },
      { label: "Looking For", value: "Internships and design projects" },
    ],
  },

  models: [
    {
      id: "anemo-meter",
      fileName: "Anemo Meter Marketing.glb",
      title: "Anemo Meter Marketing.glb",
      src: "assets/models/Anemo Meter Marketing.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.38, edgeThreshold: 28, maxEdgeTriangles: 65000, exposure: 1.12, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "Product visualization",
      role: "CAD model preparation",
      summary: "Preliminary model for marketing rendering of an Anemo Meter Station",
      tools: ["CAD", "Assembly cleanup", "Rendering prep"],
    },
    {
      id: "i4-engine",
      fileName: "I-4 Block Assembly.glb",
      title: "I-4 Block Assembly.glb",
      src: "assets/models/I-4 Block Assembly.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.38, edgeThreshold: 28, maxEdgeTriangles: 65000, exposure: 1.12, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "Assembly model",
      role: "Surface-level toy model",
      summary: "A toy model of an I-4 Engine Block",
      tools: ["Assembly modeling", "Mechanical layout", "Presentation model"],
    },
    {
      id: "landing-gear-shock",
      fileName: "Landing Gear Shock Adaptor.glb",
      title: "Landing Gear Shock Adaptor.glb",
      src: "assets/models/Landing Gear Shock Adaptor.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.42, edgeThreshold: 25, maxEdgeTriangles: 65000, exposure: 1.13, emissiveIntensity: 0.11, roughness: 0.68 },
      category: "UAV landing gear",
      role: "Adaptor design",
      summary:
        "A shock absorbing adaptor for landing gear as a project for Airntell Aerospace for a quarter scale prototype model. Utilizes truss and servo motor, with a wheel and shaft to steer.",
      tools: ["UAV hardware", "Servo integration", "Prototype design"],
    },
    {
      id: "rover-assembly",
      fileName: "Rover Assembly.glb",
      title: "Rover Assembly.glb",
      src: "assets/models/Rover Assembly.glb",
      display: { colorMode: "assembly", edgeOpacity: 0.24, edgeThreshold: 42, maxEdgeTriangles: 28000, exposure: 1.12, emissiveIntensity: 0.1, roughness: 0.72 },
      category: "Robotics",
      role: "Chassis and suspension support",
      summary:
        "Full top down assembly for Sidus Robotics, used for comprehensive design review where I worked on the chassis and suspension assembly and participated in the complete design review.",
      tools: ["Rover chassis", "Suspension", "Design review"],
    },
    {
      id: "vertical-test",
      fileName: "Vertical Test Assembly.glb",
      title: "Vertical Test Assembly.glb",
      src: "assets/models/Vertical Test Assembly.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.4, edgeThreshold: 24, maxEdgeTriangles: 90000, exposure: 1.13, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "Test rig",
      role: "Fixture modification",
      summary:
        "A modified vertical testing rig for Airntell Aerospace's UAV system. This includes safety guard for rotation in axes by the jaw structure in front and was engineered so that the point of rotation in the rig coincides with center of mass of the full uav model for computer tuning.",
      tools: ["Fixture design", "Safety guard", "Center of mass alignment"],
    },
    {
      id: "control-surface",
      fileName: "Control Surface.glb",
      title: "Control Surface.glb",
      src: "assets/models/Control Surface.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.38, edgeThreshold: 24, maxEdgeTriangles: 110000, exposure: 1.13, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "UAV wing hardware",
      role: "Surface modeling",
      summary: "Surface modelled control surfaces for UAV wings",
      tools: ["Surface modeling", "UAV wings", "CAD"],
    },
    {
      id: "landing-gear-shaft",
      fileName: "Landing Gear Shaft.glb",
      title: "Landing Gear Shaft.glb",
      src: "assets/models/Landing Gear Shaft.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.4, edgeThreshold: 24, maxEdgeTriangles: 110000, exposure: 1.13, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "UAV landing gear",
      role: "Shaft design",
      summary: "Shaft for landing gear that is assembled with the shock adaptor and helps steering with the servo.",
      tools: ["Shaft design", "Servo steering", "Mechanical fit"],
    },
    {
      id: "motor-mount",
      fileName: "Motor Mount.glb",
      title: "Motor Mount.glb",
      src: "assets/models/Motor Mount.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.4, edgeThreshold: 24, maxEdgeTriangles: 110000, exposure: 1.13, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "UAV propulsion",
      role: "Mount design",
      summary: "Mounting system for the propellor motor for UAV quarter scale version 2",
      tools: ["Motor mounting", "Prototype hardware", "CAD"],
    },
    {
      id: "rear-fuselage-adaptor",
      fileName: "RearFuselageAdaptor.glb",
      title: "RearFuselageAdaptor.glb",
      src: "assets/models/RearFuselageAdaptor.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.4, edgeThreshold: 24, maxEdgeTriangles: 110000, exposure: 1.13, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "UAV landing geometry",
      role: "Adaptor design",
      summary: "Rear adaptor designed as part of rear landing gear to help determine proper angle of attack for take-off.",
      tools: ["UAV geometry", "Adaptor design", "Assembly fit"],
    },
    {
      id: "servo-mount",
      fileName: "Servo Mount.glb",
      title: "Servo Mount.glb",
      src: "assets/models/Servo Mount.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.4, edgeThreshold: 24, maxEdgeTriangles: 110000, exposure: 1.13, emissiveIntensity: 0.1, roughness: 0.68 },
      category: "Control hardware",
      role: "Mounting plate design",
      summary: "Mounting plates for servo motors used with wing control surfaces.",
      tools: ["Servo mounting", "Sheet-style parts", "CAD"],
    },
    {
      id: "wing-model",
      fileName: "Wing Model.glb",
      title: "Wing Model.glb",
      src: "assets/models/Wing Model.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.36, edgeThreshold: 24, maxEdgeTriangles: 120000, exposure: 1.12, emissiveIntensity: 0.09, roughness: 0.7 },
      category: "3D printing",
      role: "Printable model design",
      summary:
        "3D printable model of the wings, built-in design that allows for a single-layer, singl-wall printing with no breakage between different layers.",
      tools: ["3D printing", "Wing design", "Print-oriented CAD"],
    },
    {
      id: "solar-rail",
      fileName: "Solar Rail.glb",
      title: "Solar Rail.glb",
      src: "assets/models/Solar Rail.glb",
      display: { colorMode: "assembly", edgeOpacity: 0.24, edgeThreshold: 42, maxEdgeTriangles: 35000, exposure: 1.12, emissiveIntensity: 0.1, roughness: 0.72 },
      category: "Solar mounting",
      role: "Assembly visualization",
      summary: "Solar system assembly for Natural Forces Solar used to show a new tray system for ballast blocks.",
      tools: ["Solar hardware", "Assembly model", "Design communication"],
    },
    {
      id: "test-swords",
      fileName: "Test swords.glb",
      title: "Test swords.glb",
      src: "assets/models/Test swords.glb",
      display: { color: 0xd7aa4f, colorMode: "single", edgeOpacity: 0.36, edgeThreshold: 28, maxEdgeTriangles: 65000, exposure: 1.1, emissiveIntensity: 0.09, roughness: 0.7 },
      category: "Personal project",
      role: "Print-in-place experiment",
      summary: "a recreational personal project, trying to imitate the collapsing, print in place, assembled collapsing swords.",
      tools: ["3D printing", "Mechanism experiment", "CAD"],
    },
    {
      id: "diff",
      fileName: "Diff.glb",
      title: "Diff.glb",
      src: "assets/models/Diff.glb",
      display: { color: 0x74b9df, colorMode: "single", edgeOpacity: 0.38, edgeThreshold: 28, maxEdgeTriangles: 65000, exposure: 1.1, emissiveIntensity: 0.09, roughness: 0.7 },
      category: "Rover suspension",
      role: "Suspension concept",
      summary:
        "\"Differential\" design for Sidus Robotics' rover. Named after the NASA rover suspension system and modelled after it as well.",
      tools: ["Suspension", "Rover design", "Mechanical concept"],
    },
  ],

  contact: {
    intro: "I am open to internships, mechanical design projects, prototyping work, and student team collaboration.",
    links: [
      { label: "Email", value: "aayushmans@mun.ca", href: "mailto:aayushmans@mun.ca" },
      { label: "LinkedIn", value: "linkedin.com/in/aayushman-s", href: "https://www.linkedin.com/in/aayushman-s/" },
      { label: "Resume", value: "assets/Resume.pdf", href: "assets/Resume.pdf" },
    ],
  },
};
